export const validationMessage = {
  bookTitle: "Please enter your book title.",
  enterEmail: "Please enter your email.",
  validEmail: "Please enter a valid Email ID.",
  enterPassword: "Please enter your password.",
  validPassword:
    "Password must has at least 8 characters that include at least 1 lowercase character, 1 uppercase characters, 1 number, and 1 special character (!@#$%^&*). ",
  enterOtp: "Please enter the OTP you received.",
  enterFirstName: "Please enter your first name.",
  enterLastName: "Please enter your last name.",
  enterTelephone: "Please enter your phone number.",
  enterSignupEmail: "Please enter your Email ID.",
  loginValidEmailPhone: "Please enter your registered Phone Number / Email ID.",
  confirmPasswordNotMatch: "Passwords does not match.",
  verifyRobot: "Please verify that you are not a robot.",
  firstName: "Please enter your first name.",
  validPhoneNo: "Please enter your valid phone number.",
  validPhoneNoError: "Please enter a valid 10 digit phone number.",
  contactUsMessage: "Did you forget your message? Please type your message.",
  restaurantRequired: "Please enter your restaurant name.",
  addressRequired: "Please enter the valid address.",
  contactNameRequired: "Please enter the contact name.",
  ageChecker: "Please select age.",
  locationRequired: "Please select location.",
  rapidCityRequired: "Please enter your address.",
  streetRequired: "Please enter your street name.",
  cityRequired: "Please enter your city.",
  stateRequired: "Please enter your state.",
  pincodeRequired: "Please enter the Zip code.",
  giftCardPromoCode: "Promo code is required.",
  giftCard: "Gift cards is required.",
  driverTipAmount: "Please enter a tip amount.",
  rewardValidEmail: "Please enter a valid Email ID.",
  recipientEmail: "Please enter the recipient Email ID.",
  emailSubject: "Please enter email subject.",
  rewardComment: "Did you forget your message? Please type your message.",
  giftCardBalance: "Please enter a valid gift card number.",
  eGiftCardField: "Please enter a valid code.",
  validPincodeRequired: "Please enter valid 5 digit Zip code",
  validEmailSubject: "The email subject must be at least 3 characters",
  validCommentmessage: "The message must be at least 3 characters",
};
